dist: xenial
language: python
python:
- '3.7'
install:
- pip install -r requirements-test.txt
- pip install coveralls
script:
- make ci_test
after_success: coveralls
deploy:
  provider: pypi
  user: nonamenix
  password:
    secure: gjC9Flf8JFMvDLSVsHNb7Id6uu3uPYXYwUXxVt/yl/pdKlxWbuOtXIufoIHGec8+a2lNO8X4h4PhBmsKRZUUE9F6OrxBCpYtCvYn1RkdtBROqgaViluxeg6fT1HiKRiR/R18RiJqXqN9bSoMgEonYOdDwCyqGotRhE+0EIUYt3Sm2ymUqx6OMXCJJcbjTSWoalANhaGNUw5jZDfgVczyDeOC+gk0qncXFqzwbp1Oc3tQ3iiodwlu/gymz195FSY/jp+XmVhgaEHv5iaZJsMoS+l2B8W7e3LGnNatU5fy2RPQIniThdhL9hypaebyAp8DqU3G2lusKWlzHz6ZLHa00XETQBppJxrVPBGZKNA0j8B6xSFsDJQwoA14AOzHlog/kbLd3dwP4Xp8MEDAP+ScAgBVWhjlDrsuHOCFpzSseyN5xNm8j5zukXzL+2B7rEA8KTRcI4UDtgNnt0B4I/Xmy2g/htZeLmcBy7eihehL85jo4+CtOb8wM+qbAH1g1TunSqKsl1XbT/qpuLhQn8I2R7EorCRCzRA5qqQpREHcPb4pF4oqlul8aZq2TTwOQp67Y1Y0CCJyF4jKz1xiTd0VEsXECJdjCA96dM5QiX/hrHCm+M4eKzSsGoqIc/pFB/OORB/iiG070GvHuZkW7iB4P1ctMUvLORXMstefSDdCU+4=
  distributions: sdist bdist_wheel
  on:
    tags: true
